# Generated by Django 3.1.7 on 2021-03-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_userprofile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
