# Generated by Django 3.1.7 on 2021-03-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_userprofile_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
