# Generated by Django 3.1.7 on 2021-03-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0003_auto_20210329_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
