# Generated by Django 3.1.7 on 2021-03-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0005_auto_20210330_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
