# Generated by Django 3.1.7 on 2021-04-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0008_auto_20210330_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
