# Generated by Django 3.1.7 on 2021-04-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0009_auto_20210402_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderitems',
        ),
    ]
