# Generated by Django 3.1.7 on 2021-04-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0011_remove_order_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderitems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_order.shopcart'),
        ),
    ]
