# Generated by Django 3.1.7 on 2021-04-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0012_order_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
