# Generated by Django 3.1.7 on 2021-04-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0014_auto_20210406_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
