# Generated by Django 3.1.7 on 2021-04-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0015_order_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderitems',
        ),
    ]
