# Generated by Django 3.1.7 on 2021-04-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0017_order_transactionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentId',
        ),
    ]
