# Generated by Django 3.1.7 on 2021-04-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0018_remove_order_paymentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderId',
            new_name='orderTrackingId',
        ),
    ]
