# Generated by Django 3.1.6 on 2021-03-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0006_auto_20210322_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='level',
            new_name='mptt_level',
        ),
    ]
