# Generated by Django 3.1.6 on 2021-03-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0010_auto_20210323_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
