# Generated by Django 3.1.6 on 2021-03-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0015_auto_20210325_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
