# Generated by Django 3.1.7 on 2021-04-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_auto_20210403_1044'),
        ('app_product', '0016_auto_20210326_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_user.userprofile'),
            preserve_default=False,
        ),
    ]
